-- MySQL Script generated by MySQL Workbench
-- 10/11/16 16:54:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nav_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nav_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nav_db` DEFAULT CHARACTER SET utf8 ;
USE `nav_db` ;

-- -----------------------------------------------------
-- Table `nav_db`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nav_db`.`utilisateur` (
  `iDutilisateur` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `mdp` VARCHAR(45) NULL,
  PRIMARY KEY (`iDutilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nav_db`.`type_alerte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nav_db`.`type_alerte` (
  `iDtype_alerte` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`iDtype_alerte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nav_db`.`alertes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nav_db`.`alertes` (
  `iDalertes` INT NOT NULL,
  `longitude` FLOAT NULL,
  `latitude` FLOAT NULL,
  `nombre_notification` INT NULL,
  `type_alerte_iDtype_alerte` INT NOT NULL,
  PRIMARY KEY (`iDalertes`),
  INDEX `fk_alertes_type_alerte1_idx` (`type_alerte_iDtype_alerte` ASC),
  CONSTRAINT `fk_alertes_type_alerte1`
    FOREIGN KEY (`type_alerte_iDtype_alerte`)
    REFERENCES `nav_db`.`type_alerte` (`iDtype_alerte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nav_db`.`alerte_utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nav_db`.`alerte_utilisateur` (
  `alertes_iDalertes` INT NOT NULL,
  `utilisateur_iDutilisateur` INT NOT NULL,
  `date` DATETIME(6) NULL,
  PRIMARY KEY (`alertes_iDalertes`, `utilisateur_iDutilisateur`),
  INDEX `fk_alerte_utilisateur_alertes_idx` (`alertes_iDalertes` ASC),
  INDEX `fk_alerte_utilisateur_utilisateur1_idx` (`utilisateur_iDutilisateur` ASC),
  CONSTRAINT `fk_alerte_utilisateur_alertes`
    FOREIGN KEY (`alertes_iDalertes`)
    REFERENCES `nav_db`.`alertes` (`iDalertes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alerte_utilisateur_utilisateur1`
    FOREIGN KEY (`utilisateur_iDutilisateur`)
    REFERENCES `nav_db`.`utilisateur` (`iDutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
